# docker-compose.yml

services:
  postgres:
    image: postgres:15
    container_name: music_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    container_name: music_auth
    depends_on:
      - postgres
    env_file:
      - "auth/.env"
    build:
      context: .
      dockerfile: ./infra/Dockerfile
      args:
        APPLICATION_NAME: ${APPLICATION_NAME}
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

volumes:
  postgres_data: